In [2]:
import numpy as np
import cv2

import os
import glob

In [5]:
# Locate points of the documents or object which you want to transform 
img = cv2.imread('/home/shane/camera0_100.jpg', 1) 
# pts1 = np.float32([[556, 433], [727, 433], [872, 585], [409,586]]) 
# ratio=1.4
# cardH = np.sqrt((pts1[2][0]-pts1[1][0])*(pts1[2][0]-pts1[1][0])+(pts1[2][1]-pts1[1][1])*(pts1[2][1]-pts1[1][1]))
# cardW=ratio*cardH
# cardH = int(cardH)
# cardW = int(cardW)
# pts2 = np.float32([[0,cardW - cardH], [cardW, cardW - cardH], [cardW, cardW], [0, cardW]])
pts1 = np.float32([[289, 404],
    [990, 404],
    [935, 982],
    [348, 982]])
pts2 = np.float32([[289, 404],
    [990, 404],
    [924, 914],
    [359, 914]])
matrix = cv2.getPerspectiveTransform(pts1, pts2) 
result = cv2.warpPerspective(img, matrix, (1280, 1280)) 

In [6]:
cv2.imshow('test', result)
cv2.waitKey(0)  

-1

In [4]:
print(matrix)

[[-4.47272388e-01 -4.29732294e-01  4.34757531e+02]
 [ 3.09871541e-04 -1.21611752e+00  5.04501161e+02]
 [ 3.68894692e-06 -2.91646672e-03  1.00000000e+00]]


In [5]:
print(cardW)
print(cardH)

294
210


In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren&#39;t special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you&#39;re Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it&#39;s a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let&#39;s do more of those!


In [2]:
-1 % 6

5